version: '3'

services: 
  nginx:
    image: my-nginx
    container_name: my-nginx
    restart: always
    ports: 
      - '8080:80'
    networks: 
      - my_net

networks: 
  my_net:
    external: true